export type Platform='kalshi'|'polymarket';
export type Market={id:string;platform:Platform;title:string;category:string;categoryInferred:boolean;end:string|null;yesAsk:number|null;noAsk:number|null;volume:number;volumeUnit:string;fetchedAt:number;url:string;rules:string;tokens?:string[];quoteWarning?:string;combo?:boolean};
export type Forecast={platform:Platform;marketId:string;probabilityYes:number;source:string;sourceUrl:string;updatedAt:string;expiresAt:string;rationale:string;ai?:{yes:number;no:number;model:string}};
export type Position={key:string;market:Market;side:'YES'|'NO';ask:number|null;p:number|null;raw:number|null;net:number|null;score:number|null;forecast:Forecast|null;fresh:boolean;forecastFresh:boolean};
export const categories=['All categories','Sports','Politics','Crypto','Economics','Weather','Culture','Technology','Other'];
export function classify(text:string){const t=text.toLowerCase();if(/\b(bitcoin|ethereum|crypto|btc|eth|solana|xrp|dogecoin)\b/.test(t))return 'Crypto';if(/\b(nfl|nba|mlb|nhl|soccer|football|basketball|baseball|tennis|golf|ufc|sports|world cup|premier league|touchdown|championship|super bowl|fifa)\b|\bvs\.?\s/.test(t))return 'Sports';if(/\b(election|president|trump|congress|senate|democrat|republican|politic|minister|governor|putin|zelensky|xi jinping|ceasefire|iran|israel|war|nominee)\b/.test(t))return 'Politics';if(/\b(inflation|gdp|fed|interest rate|unemployment|recession|cpi|economics|economy|finance|oil|treasury)\b/.test(t))return 'Economics';if(/\b(weather|temperature|rain|snow|hurricane|climate|high temp|low temp)\b/.test(t))return 'Weather';if(/\b(ai|openai|technology|spacex|apple|google|nvidia|tesla)\b/.test(t))return 'Technology';if(/\b(oscar|movie|music|album|box office|grammy|culture|entertainment)\b/.test(t))return 'Culture';return 'Other'}
export function price(v:unknown){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)&&n>0&&n<1?n:null}
export function parseForecasts(value:unknown):Forecast[]{const obj=value as {forecasts?:unknown};const rows=Array.isArray(value)?value:obj?.forecasts;if(!Array.isArray(rows)||rows.length>100000)throw new Error('Expected a forecasts array with at most 100,000 entries.');const seen=new Set<string>();return rows.map((raw,i)=>{const f=raw as Forecast;const bad=(msg:string)=>{throw new Error(`Forecast ${i+1}: ${msg}`)};if(!f||!['kalshi','polymarket'].includes(f.platform)||typeof f.marketId!=='string'||!f.marketId.trim())bad('platform and marketId are required.');if(typeof f.probabilityYes!=='number'||!Number.isFinite(f.probabilityYes)||f.probabilityYes<0||f.probabilityYes>1)bad('probabilityYes must be between 0 and 1.');if(typeof f.source!=='string'||!f.source.trim()||typeof f.rationale!=='string'||!f.rationale.trim())bad('source and rationale are required.');try{if(new URL(f.sourceUrl).protocol!=='https:')bad('sourceUrl must use HTTPS.')}catch{bad('sourceUrl must use HTTPS.')}const at=Date.parse(f.updatedAt),expires=Date.parse(f.expiresAt);if(!Number.isFinite(at)||!Number.isFinite(expires)||expires<=at||at>Date.now()+300000)bad('provide valid updatedAt and expiresAt timestamps, with expiry after update.');if(f.ai){if(typeof f.ai.model!=='string'||!f.ai.model.trim()||![f.ai.yes,f.ai.no].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=1&&n<=10))bad('AI ratings must be 1–10 and identify the model.');}const key=f.platform+':'+f.marketId;if(seen.has(key))bad('duplicate market ID.');seen.add(key);return f})}
export function positions(markets:Market[],forecasts:Forecast[],costCents:number,now=Date.now()):Position[]{const map=new Map(forecasts.map(f=>[f.platform+':'+f.marketId,f]));return markets.flatMap(m=>{const f=map.get(m.platform+':'+m.id)||null;const forecastFresh=!!f&&Date.parse(f.expiresAt)>now&&Date.parse(f.updatedAt)<=now+300000;return (['YES','NO'] as const).map(side=>{const ask=side==='YES'?m.yesAsk:m.noAsk;const p=forecastFresh&&f?(side==='YES'?f.probabilityYes:1-f.probabilityYes):null;const raw=p!==null&&ask!==null?100*(p-ask):null;return {key:m.platform+':'+m.id+':'+side,market:m,side,ask,p,raw,net:raw===null?null:raw-costCents,score:forecastFresh&&f?.ai?(side==='YES'?f.ai.yes:f.ai.no):null,forecast:f,fresh:now-m.fetchedAt<=120000&&(!m.end||Date.parse(m.end)>now),forecastFresh}})})}
export function qualifies(p:Position,threshold:number,mode:'net'|'raw'='net'){return p.fresh&&p.forecastFresh&&p[mode]!==null&&p[mode]!>threshold+1e-9}
export function horizonMatches(end:string|null,horizon:string,now=Date.now()){if(horizon==='all')return true;if(!end||!Number.isFinite(Date.parse(end)))return horizon==='unknown';const days=(Date.parse(end)-now)/86400000;if(days<=0)return false;if(horizon==='day')return days<=1;if(horizon==='week')return days>1&&days<=7;if(horizon==='month')return days>7&&days<=30;if(horizon==='quarter')return days>30&&days<=90;if(horizon==='long')return days>90;return false}
export function comparePositions(a:Position,b:Position,sort:string){const val=(p:Position)=>sort.startsWith('gap')?p.net:sort==='ai'?p.score:sort==='closing'?(p.market.end?Date.parse(p.market.end):null):p.market.volume;const x=val(a),y=val(b);if(x===null&&y===null)return a.key.localeCompare(b.key);if(x===null)return 1;if(y===null)return -1;return (sort==='gap-asc'||sort==='closing'?x-y:y-x)||a.key.localeCompare(b.key)}
